ANACompute/src/beans/ProductDataBaseService.java
package beans;

import java.sql.Connection;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import javax.ejb.Local;
import javax.ejb.Stateless;
import javax.enterprise.inject.Alternative;

import business.ProductDataBaseInterface;

import java.sql.Statement;


@Stateless
@Local
@Alternative
public class ProductDataBaseService implements ProductDataBaseInterface{
	
	
	
	
	public void addProduct(Product pd) {
		System.out.println("Created a new product: " + pd.toString());
		// Connect to database
		String dbURL = "jdbc:mysql://localhost:3306/anacompute";
		String username = "root";
		String password = "root";
		Connection c = null;
		PreparedStatement stmt = null;
		int rowsAffected = 0;
		try {
			c = DriverManager.getConnection(dbURL, username, password);
			// create a SQL statement
			stmt = c.prepareStatement(
					"insert into anacompute.product (productName, productDiscription, productAmount, productCost, imageUrl) values (?,?,?,?,?)");
			stmt.setString(1, pd.getProductName());
			stmt.setString(2, pd.getProductDiscription());
			stmt.setInt(3, pd.getProductAmount());
			stmt.setDouble(4, pd.getProductCost());
			stmt.setString(5, pd.getImageUrl());
			// execute the statemant
			rowsAffected = stmt.executeUpdate();

			// process the rows effected
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		
		System.out.println("SUCCESS!! Rows affected " + rowsAffected);
		try {
			c.close();
			stmt.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
	}
	
	

	public ArrayList<Product> getAllProducts() {
		return this.readAllProducts();
	}
	
	
	public void decreaseOne(Product pd) {
		// Connect to database
		String dbURL = "jdbc:mysql://localhost:3306/anacompute";
		String username = "root";
		String password = "root";

		Connection c = null;
		Statement stmt = null;
		ResultSet rs = null;
		int rowsAffected = 0;
		
		try {
			//Connect to database
			c = DriverManager.getConnection(dbURL, username, password);
			
			// create a SQL statement 
			stmt = c.createStatement();
			// execute the statemant
			String prep = "update anacompute.product set productAmount = '" + (pd.getProductAmount() - 1)+"' where productID = '" + pd.getProductID() +"'" ;
			rowsAffected = stmt.executeUpdate(prep);

			System.out.println(pd.toString());
		
			
			
			
			
		} catch (SQLException e) {
	
			e.printStackTrace();
		} finally {
			//close the connection
			try {
				stmt.close();
				c.close();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		
			
		}
		
		
		
	}
	

	public boolean checkProduct(Product pd) {
		boolean ct = false;
		// Connect to database
		String dbURL = "jdbc:mysql://localhost:3306/anacompute";
		String username = "root";
		String password = "root";

		Connection c = null;
		Statement stmt = null;
		ResultSet rs = null;
		try {
			// Connect to database
			c = DriverManager.getConnection(dbURL, username, password);
			//System.out.println("Connection successful!");
			//System.out.println("Connected to : " + dbURL);

			// create a SQL statement
			stmt = c.createStatement();
			// execute the statemant
			rs = stmt.executeQuery("select * from anacompute.product");

			// process the rows in the result set
			while (rs.next()) {
				if (rs.getInt("productID") == pd.getProductID()) {
					if (rs.getInt("productAmount") > 0) {
						//In Stock!
						System.out.println("This item is in stock!");
						decreaseOne(pd);
					} else {
						//Out of stock :(
						System.out.println("This item is out of stock!");
					}
				}

			}
		} catch (SQLException e) {
			System.out.println("Connection unsuccessful!");
			e.printStackTrace();
		} finally {
			// close the connection
			try {
				rs.close();
				stmt.close();
				c.close();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}
		return ct;
		
		
	}

	public ArrayList<Product> readAllProducts() {
		// Connect to database
		String dbURL = "jdbc:mysql://localhost:3306/anacompute";
		String username = "root";
		String password = "root";

		Connection c = null;
		Statement stmt = null;
		ResultSet rs = null;
		ArrayList<Product> p = new ArrayList<Product>();
		try {
			// Connect to database
			c = DriverManager.getConnection(dbURL, username, password);
			//System.out.println("Connection successful!");
		//	System.out.println("Connected to : " + dbURL);

			// create a SQL statement
			stmt = c.createStatement();
			// execute the statemant
			rs = stmt.executeQuery("select * from anacompute.product");

			// process the rows in the result set
			p.clear();
			while (rs.next()) {
				Product np = new Product();
				np.setProductID(Integer.parseInt(rs.getString("productID").toString()));
				np.setProductName(rs.getString("productName"));
				np.setProductDiscription(rs.getString("productDiscription"));
				np.setProductAmount(Integer.parseInt(rs.getString("productAmount").toString()));
				np.setProductCost(Double.parseDouble(rs.getString("productCost").toString()));
				np.setImageUrl(rs.getString("imageUrl"));
				//System.out.println(np.toString());
				p.add(np);

			}
		} catch (SQLException e) {
			//System.out.println("Connection unsuccessful!");
			e.printStackTrace();
		} finally {
			// close the connection
			try {
				rs.close();
				
				stmt.close();

				c.close();
			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		

		}
		
		
		return p;
	}

}

ANACompute/src/controllers/LoginController.java
package controllers;


import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import beans.User;
import business.UserBusinessServiceInterface;

@ManagedBean
public class LoginController {
	
	public static User loggedUser = new User();
    @Inject
    UserBusinessServiceInterface UDBC;
    
    int attempts = 3;
	public String onSubmit() {
		String register = "CreateAccount.xhtml";
		String success = "Home.xhtml";
		String incorrect = "Login.xhtml";
		String decided = "";
		//Get the user value from the input form;
		FacesContext context = FacesContext.getCurrentInstance();
		User user = context.getApplication().evaluateExpressionGet(context, "#{user}", User.class);
		

		// Send the information to the POST request
		FacesContext.getCurrentInstance().getExternalContext().getRequestMap().put("user", user);
		System.out.println("You clicked the submit button. Sending information to the database!" + user.getUsername() + " " + user.getPassword());
		
		
			boolean check = UDBC.check(user.getUsername(), user.getPassword());
			if (check) {
				loggedUser.setUsername(user.getUsername());
				decided = success;
			} else {
				decided = incorrect;
				attempts--;
				System.out.println(attempts);
				if (attempts < 0) {
					decided = register;
					attempts = 3;
				}
			}
		
		
		return decided;
	}

}

ANACompute/WebContent/CreateAccount.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

	<body>
<ui:composition template="/layouts/commonLayouts.xhtml">
	<ui:define name="content">
	<link rel="stylesheet" href="css/style.css" type="text/css" />

			<h:form class="noWrap">
			<p>
				First Name:
				<h:inputText value="#{user.firstName}" />
				<font color = "red">#{formController.user.firstName}</font>
			</p>
			<p>
				Last Name:
				<h:inputText value="#{user.lastName}" />
				<font color = "red">#{formController.user.lastName}</font>
			</p>
			<p>
				Email:
				<h:inputText value="#{user.email}" />
				<font color = "red">#{formController.user.email}</font>
			</p>
			<p>
				Address:
				<h:inputText value="#{user.address}" />
				<font color = "red">#{formController.user.address}</font>
			</p>
			<p>
				Phone Number:
				<h:inputText value="#{user.phoneNumber}" />
				<font color = "red">#{formController.user.phoneNumber}</font>
			</p>
			<p>
				Username:
				<h:inputText value="#{user.username}" />
				<font color = "red">#{formController.user.username}</font>
			</p>
			<p>
				Password:
				<h:inputText value="#{user.password}" />
				<font color = "red">#{formController.user.password}</font>
			</p>
			<h:commandButton action="#{formController.onSubmit()}" value="Submit" />
			<h:commandButton action="Login.xhtml" value="Back" />
		</h:form>

	</ui:define>
</ui:composition>

	</body>



</html>

ANACompute/WebContent/CreateProduct.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">


<ui:composition template="/layouts/commonLayouts.xhtml">
	<ui:define name="content">
		<h:head>
			<link rel="stylesheet" href="css/style.css" type="text/css" />
		</h:head>
		<h:form>
			<div>
				<h:commandButton
					action="#{navigationController.onSubmit('Home.xhtml')}"
					value="Back" />
			</div>
		</h:form>
		<div>
			<h:form class="noWrap">
				<p>Create Product</p>
				<p>
					Product Name:
					<h:inputText value="#{product.productName}" />
					
				</p>
				<p>
					Product Description:
					<h:inputText value="#{product.productDiscription}" />
				</p>
				<p>
					Product Amount
					<h:inputText value="#{product.productAmount}" />

				</p>
				<p>
					Product Cost
					<h:inputText value="#{product.productCost}" />

				</p>
				<p>
					Product ImageURL
					<h:inputText value="#{product.imageUrl}" />
					<h:graphicImage value="" width="70px" height="70px" />

				</p>
				<h:commandButton
					action="#{storeManager.CreateNewProduct()}"
					value="Save" />

			</h:form>
		</div>




	</ui:define>
</ui:composition>
</html>

ANACompute/WebContent/Edit.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">


<ui:composition template="/layouts/commonLayouts.xhtml">
	<ui:define name="content">
		<h:head>
			<link rel="stylesheet" href="css/style.css" type="text/css" />
		</h:head>
		<h:form>
			<div>
				<h:commandButton
					action="#{navigationController.onSubmit('Home.xhtml')}"
					value="Back" />
			</div>
		</h:form>
		<div>
			<h:form class="noWrap">
				<p>Edit Product</p>
				<p>#{product.toString()}</p>
				<p>
					Product Name:
					<h:inputText value="#{product.productName}" />
				</p>
				<p>
					Product Description:
				<textarea id="txtArea" rows="10" cols="40">
					#{product.productDiscription}
				</textarea>
				</p>
				<p>
					Product Amount
					<h:inputText value="#{product.productAmount}" />

				</p>
				<p>
					Product Cost
					<h:inputText value="#{product.productCost}" />

				</p>
				<p>
					Product ImageURL
					<h:inputText value="#{product.imageUrl}" />
					<h:graphicImage value="#{product.imageUrl}" width="70px" height="70px" />

				</p>
				<h:commandButton
					action="#{navigationController.onSubmit('Home.xhtml')}"
					value="Save" />

			</h:form>
		</div>




	</ui:define>
</ui:composition>
</html>

ANACompute/WebContent/Home.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">


<ui:composition template="/layouts/commonLayouts.xhtml">

	<ui:define name="content">
		<link rel="stylesheet" href="css/style.css" type="text/css" />

		<h:form class="searchHeader">
			<h:inputText value="" />
			<h:commandButton action="Home.xhtml" value="Search" />
		</h:form>
		<h:form class="searchHeader">
				<h:commandButton
					action="#{navigationController.adminOnSubmit('CreateProduct.xhtml')}"
					value="Create New Product" />
			</h:form>
		<body>
		
			
			<h:dataTable value="#{storeManager.allProducts}" var="o">
				<h:column class="col1">
					<div class="card">

						<f:facet name="header"></f:facet>
						<h:graphicImage value="#{o.imageUrl}" width="70px" height="70px" />
						<h1>#{o.productName}</h1>
						<p>$#{o.productCost} There are #{o.productAmount} in stock!</p>
						<p>#{o.productDiscription}</p>
						<h:form>
							<p>
							<h:commandButton action="#{storeManager.purchase(o)}"
									value="Buy" styleClass= "button"/>
									
							</p>
						</h:form>
					</div>
				</h:column>


			</h:dataTable>
		</body>
	</ui:define>
</ui:composition>






</html>

ANACompute/WebContent/Login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">

<body>
	<ui:composition template="/layouts/commonLayouts.xhtml">
		
		<ui:define name="content">
		<link rel="stylesheet" href="css/style.css" type="text/css" />
		
		<h:form class="noWrap">
		<center>
			<p>
				Username:
				<h:inputText value="#{user.username}" />
			</p>
			<p>
				Password:
				<h:inputSecret value="#{user.password}" />
			</p>
			
			<h:commandButton action="#{loginController.onSubmit()}"
					value="Login" />
			<h:commandButton action="CreateAccount.xhtml"
					value="Register" />
					</center>
		</h:form>
		
		</ui:define>
	</ui:composition>
</body>



<ui:define name="footer">This is the override footer</ui:define>



</html>

ANACompute/WebContent/Response.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html">


<head>
<title><ui:insert name="PageTitle">Page Title</ui:insert></title>

</head>



<body>
	<ui:composition template="/layouts/commonLayouts.xhtml">
	
	<ui:define name="content">
	<link rel="stylesheet" type="text/css" href="css/style.css" media="all" />
	<h:form class="noWrap">
		<p>First Name: #{user.firstName}</p>
		<p>Last Name: #{user.lastName}</p>
		<p>Email: #{user.email}</p>
		<p>Address: #{user.address}</p>
		<p>Phone Number: #{user.phoneNumber}</p>
		<p>Username: #{user.username}</p>
		<p>Password: #{user.password}</p>
		<h:commandButton action="CreateAccount.xhtml"
			value="Back" />
		<h:commandButton action="#{registerConfirmController.onSubmit()}"
			value="Submit" />
		<h:messages />

	</h:form>
		</ui:define>


	</ui:composition>


</body>








</html>